export const countryNames = {
  "CYP": "Cyprus",
  "ECU": "Ecuador",
  "GRC": "Greece",
  "IDN": "Indonesia",
  "JOR": "Jordan",
  "LBY": "Libya",
  "MAC": "Macau",
  "MDV": "Maldives",
  "NZL": "New Zealand",
  "NGA": "Nigeria",
  "PHL": "Philippines",
  "SRB": "Serbia",
  "THA": "Thailand",
  "TUN": "Tunisia",
  "GBR": "United Kingdom",
  "UZB": "Uzbekistan",
  "NIR": "Northern Ireland",
  "CHN": "China",
  "SGP": "Singapore",
  "VNM": "Vietnam",
  "AUS": "Australia",
  "CAN": "Canada",
  "ETH": "Ethiopia",
  "KEN": "Kenya",
  "NLD": "Netherlands",
  "ZWE": "Zimbabwe",
  "AND": "Andorra",
  "ARG": "Argentina",
  "BGD": "Bangladesh",
  "ARM": "Armenia",
  "BOL": "Bolivia",
  "BRA": "Brazil",
  "MMR": "Myanmar",
  "CHL": "Chile",
  "TWN": "Taiwan",
  "COL": "Colombia",
  "CZE": "Czech Republic",
  "DEU": "Germany",
  "HKG": "Hong Kong",
  "IRN": "Iran",
  "JPN": "Japan",
  "KAZ": "Kazakhstan",
  "KOR": "South Korea",
  "KGZ": "Kyrgyzstan",
  "LBN": "Lebanon",
  "MEX": "Mexico",
  "PAK": "Pakistan",
  "PER": "Peru",
  "PRI": "Puerto Rico",
  "ROU": "Romania",
  "RUS": "Russia",
  "SVK": "Slovakia",
  "TUR": "Turkey",
  "UKR": "Ukraine",
  "EGY": "Egypt",
  "USA": "United States",
  "URY": "Uruguay",
  "IND": "India",
  "MNG": "Mongolia",
  "NIC": "Nicaragua",
  "MAR": "Morocco",
  "VEN": "Venezuela",
  "IRQ": "Iraq",
  "TJK": "Tajikistan",
  "GTM": "Guatemala",
  "MYS": "Malaysia",
  "ALB": "Albania",
  "AZE": "Azerbaijan",
  "BFA": "Burkina Faso",
  "BGR": "Bulgaria",
  "BIH": "Bosnia and Herzegovina",
  "BLR": "Belarus",
  "CHE": "Switzerland",
  "DOM": "Dominican Republic",
  "DZA": "Algeria",
  "ESP": "Spain",
  "EST": "Estonia",
  "FIN": "Finland",
  "FRA": "France",
  "GEO": "Georgia",
  "GHA": "Ghana",
  "HTI": "Haiti",
  "HUN": "Hungary",
  "ITA": "Italy",
  "KWT": "Kuwait",
  "LTU": "Lithuania",
  "LVA": "Latvia",
  "MDA": "Moldova",
  "MKD": "North Macedonia",
  "MLI": "Mali",
  "MNE": "Montenegro",
  "NOR": "Norway",
  "POL": "Poland",
  "PSE": "Palestine",
  "QAT": "Qatar",
  "RWA": "Rwanda",
  "SAU": "Saudi Arabia",
  "SLV": "El Salvador",
  "SVN": "Slovenia",
  "SWE": "Sweden",
  "TTO": "Trinidad and Tobago",
  "TZA": "Tanzania",
  "UGA": "Uganda",
  "YEM": "Yemen",
  "ZAF": "South Africa",
  "ZMB": "Zambia",
};

export const getCountryName = (code) => {
  return countryNames[code] || code;
};
